#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

IMAGE=${REPO}/harvester-vm-import-controller:${TAG}
DOCKERFILE=package/Dockerfile

buildx build --load \
  -f ${DOCKERFILE} -t ${IMAGE} .

echo Built ${IMAGE}
